name: gh_pages

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: setup flutter environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.1'
  build:
    name: build flutter for web
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: flutter --version
      - run: flutter pub get
      - name: run build
        run: flutter build web
  deploy:
    name: deploy github pages
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GithubPages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages